import React from "react";

const page = () => {
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
      <h1 className="text-6xl font-bold mb-16 mt-20">Important Disclosure</h1>
      <p>
        THIS WEBSITE (THE "WEBSITE") IS INTENDED SOLELY TO PROVIDE GENERAL
        INFORMATION ABOUT PROTOCOL LABS VENTURE STUDIO, ITS SERVICES TO
        ENTREPRENEURS AND MANAGEMENT TEAMS, AND ITS PERSONNEL. THE CONTENT
        PROVIDED ON THIS WEBSITE, INCLUDING BUT NOT LIMITED TO INVESTMENT,
        ACCOUNTING, TAX, OR LEGAL INFORMATION, DOES NOT CONSTITUTE PROFESSIONAL
        ADVICE. NONE OF THOSE ITEMS NOR SHOULD IT BE CONSTRUED AS A
        RECOMMENDATION TO BUY, SELL, OR HOLD ANY SECURITY OR OTHER INVESTMENT,
        OR TO ADOPT ANY SPECIFIC INVESTMENT STYLE OR STRATEGY. THE OPINIONS AND
        VIEWS EXPRESSED IN ANY POSTS, PODCASTS, VIDEOS, AND ON SOCIAL MEDIA
        PLATFORMS ARE SOLELY THOSE OF THE INDIVIDUALS QUOTED AND DO NOT
        REPRESENT THE VIEWS OF PROTOCOL LABS VENTURE STUDIO. PROTOCOL LABS
        VENTURE STUDIO RESERVES THE RIGHT TO MODIFY OR AMEND ANY OPINIONS
        EXPRESSED ON THIS WEBSITE AT ANY TIME WITHOUT NOTICE. THE CONTENTS IN
        HERE — AND AVAILABLE ON ANY ASSOCIATED DISTRIBUTION PLATFORMS AND ANY
        PUBLIC PROTOCOL LABS VENTURE STUDIO ONLINE SOCIAL MEDIA ACCOUNTS,
        PLATFORMS AND SITES (INCLUDING THE PERSONAL ACCOUNTS OF PROTOCOL LABS
        VENTURE STUDIO'S EMPLOYEES COLLECTIVELY, "CONTENT DISTRIBUTION OUTLETS")
        — SHOULD NOT BE CONSTRUED AS OR RELIED UPON IN ANY MANNER AS INVESTMENT,
        LEGAL, TAX, OR OTHER ADVICE. YOU SHOULD CONSULT YOUR OWN ADVISERS AS TO
        LEGAL, BUSINESS, TAX, AND OTHER RELATED MATTERS CONCERNING ANY
        INVESTMENT. ANY PROJECTIONS, ESTIMATES, FORECASTS, TARGETS, PROSPECTS
        AND/OR OPINIONS EXPRESSED IN THESE MATERIALS ARE SUBJECT TO CHANGE
        WITHOUT NOTICE AND MAY DIFFER OR BE CONTRARY TO OPINIONS EXPRESSED BY
        OTHERS. ANY CHARTS PROVIDED ARE FOR INFORMATIONAL PURPOSES ONLY AND
        SHOULD NOT BE RELIED UPON WHEN MAKING INVESTMENT DECISIONS.
      </p>
    </div>
  );
};

export default page;
